server:
  port: 8180

spring:
  application:
    name: dubbo-provider
  cloud:
    nacos:
      discovery:
        username: nacos
        password: Aa111111
        server-addr: 124.221.99.45:8848

dubbo:
  registry:
    address: nacos://124.221.99.45:8848 #注册地址
  application:
    name: dubbo-provider #应用名
  protocol:
    name: dubbo #dubbo协议
    port: 20880 #协议端口
  scan:
    base-packages: com.yt.cloud #扫包范围
  provider:
    timeout: 30000 #超时时间