server:
  port: 8000
  context-path: /

#spring:
#  datasource:
#    name: test
#    url: jdbc:oracle:thin:@127.0.0.1:1521/myorcl
#    username: system
#    password: 111111
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: oracle.jdbc.driver.OracleDriver

spring:
  datasource:
    name: LYT_DB
    url: jdbc:oracle:thin:@47.98.115.140:1521/orcl
    username: lyt
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.yt.model

#监控端点
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@

#logging:
#  file: F:\app\logs\log.log
#  level: DEBUG

#logback_logpath: F:\app\logs
