server:
  port: 8182

spring:
  cloud:
    gateway:
      routes:
        - predicates:
            - Path=/gateway/**  #匹配规则
          uri: http://localhost:8180/**    #服务1的访问地址
          filters:
            - StripPrefix=1
        - id: dubbo-provider             #路由的ID，没有固定规则但要求唯一，建议配合服务名
          predicates:
            - Path=/**      #断言，路径相匹配的进行路由
          uri: lb://dubbo-provider    #匹配后提供服务的路由地址
      discovery:
        locator:
          enabled: true
    nacos:
      discovery:
        server-addr: 124.221.99.45:8848
        username: nacos
        password: nacos
        namespace: 8d16f8b3-f17e-4045-9828-c95e239f5594
  application:
    name: nacos-gateway

